@startuml
'https://plantuml.com/class-diagram

class A {
public int x
}
class B {
public int y
}
class C {
public int z
}

B -up-|> A
C -up-|> B

class Box<T> {
private T value
T get()
void set(T value)
}
@enduml